### ISSUE TITLE
Panic on Firefox

### ISSUE THREAD

**Issue by intendednull** [mrk-its/bevy_webgl2#34]
Getting this error when trying to run examples on firefox:
```
'called `Result::unwrap()` on an `Err` value: "ERROR: 0:346: \'for\' : Invalid condition\n"', /home/intendednull/.cargo/git/checkouts/bevy_webgl2-bb0e279954ae087c/33dda29/src/renderer/webgl2_render_resource_context.rs:77:81
```
`sprite.rs` works, however `3d_scene.rs` and `breakout.rs` do not. Let me know if I should test any other examples. Problem is present on latest release, master, and dev branch. 

It was working until FF updated, so maybe a configuration setting was tweaked? Tried toggling every webgl2 setting I could find with no luck. Also tried a fresh install of both FF developer and stable. 

System details:
```
$ screenfetch -n
 OS: Manjaro 21.0 Ornara
 Kernel: x86_64 Linux 5.10.23-1-MANJARO
 Shell: fish 3.1.2
 WM: XMonad
 CPU: AMD Ryzen 7 3700X 8-Core @ 16x 3.6GHz
 GPU: GeForce GTX 1070 Ti
 RAM: 10674MiB / 24034MiB
$ firefox-developer-edition --version
Mozilla Firefox 87.0b9
```

WebGL2 does appear to be enabled on my system:
![image](https://user-images.githubusercontent.com/27320363/114111921-1336c080-9890-11eb-9ae6-2f070d9d95cc.png)

**Comment by billyb2** [comment]
Hey, are you still having this issue?

**Comment by intendednull** [comment]
@billyb2 yes, also had a few updates from firefox with no change

**Comment by billyb2** [comment]
@intendednull that's very strange. I'm using Arch and the latest version of Firefox with no issue (and way less RAM then you :( )What version of Firefox did it work in, and when did it stop? Could be a bug with Firefox itself. Also, have you tried using a Chromium based browser to see if it works there?

**Comment by intendednull** [comment]
@billyb2 agreed, not completely sure on the version, think the one I posted above is pretty close. Does work on chromium, which is what I've been using since.

I even tried a switching from developer edition to stable with no luck. So it seems specific version doesn't matter. Makes me think my installation is corrupt, but a fresh install should have fixed that  :/

**Comment by billyb2** [comment]
Have you made sure to clear all configurations when doing a fresh install? Or what about booting off a live stick w. Firefox on it and seeing if it'll run.

**Comment by intendednull** [comment]
Thanks for the suggestions, will try and get back to you.

**Comment by NiklasEi** [comment]
I am getting a very similar error in both Firefox and Google Chrome. It has a different error message, but comes from the same point in `bevy_webgl2`:
```
panicked at 'called `Result::unwrap()` on an `Err` value: "ERROR: 0:1: '\n' : invalid version directive\nERROR: 0:5: 'layout' : syntax error\n\u{0}"', /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_webgl2-0.5.2/src/renderer/webgl2_render_resource_context.rs:77:81
```

**Comment by intendednull** [comment]
A completely fresh reinstall fixed this issue for me. Seems like bad cache maybe.

**Comment by billyb2** [comment]
@intendednull Are you gonna close this? That's a weird issue for sure though.

**Comment by intendednull** [comment]
Might as well. If @NiklasEi's problem isn't fixed with a fresh install, they can open a new one, as it would seem to be unrelated.
