### ISSUE TITLE
Add support for bevy_prototype_lyon shaders

### ISSUE THREAD

**Issue by alyti** [mrk-its/bevy_webgl2#37]
Currently bevy_prototype_lyon plugin panics on web due to only having modern glsl shaders, I feel like it would make more sense to perform the pipeline swap for them here instead of duplicating the codebases for this functionality.

Related: https://github.com/Nilirad/bevy_prototype_lyon/issues/93

**Comment by mrk-its** [comment]
bevy_prototype_lyon should simply provide "#version 300 es" shaders when linked with bevy_webgl2. I see these shaders are very simple, so whole thing should be very strightforward.

**Comment by alyti** [comment]
I've made a pr on bevy_prototype_lyon side and hopefully will get it working there, thanks.
