### ISSUE TITLE
Latest Bevy Dev Commit Doesn't Build w. bevy_webgl2

### ISSUE THREAD

**Issue by billyb2** [mrk-its/bevy_webgl2#40]
When patching bevy_webgl2 to use [the latest development commit of Bevy](https://github.com/bevyengine/bevy/commit/afaf4ad3daa01a2be529c19fc183ae8ddd2a330f), the build fails with a dependency conflict with js-sys. I suspet it has to do with upgrading wgpu to 0.8.

**Comment by mockersf** [comment]
this dependency can probably be less constrained now: https://github.com/mrk-its/bevy_webgl2/blob/fd5b83d8cd8b28b428772ef582a3d4a8de2b7c72/Cargo.toml#L30

**Comment by billyb2** [comment]
So changing it to 0.2.73 would help? Like in a PR or something.

**Comment by billyb2** [comment]
I tried simply updating wasm-bindgen, js-sys, and web-sys, and then using the latest Bevy commit, but it has a lot of breaking changes.

**Comment by mrk-its** [comment]
@billyb2 @mockersf `master` branch of bevy_webgl2 works with current `main` branch of bevy.
I've also created v0.5 branch for 0.5.x releases

**Comment by billyb2** [comment]
Thank you
