### ISSUE TITLE
Opengl native

### ISSUE THREAD

**Issue by bekraoui** [mrk-its/bevy_webgl2#53]
Would it be easy to adapt this package to work with opengl as the native webGPU on bevy does not recognize my GPU  (quadro 2000)?

**Comment by mrk-its** [comment]
Latest wgpu has GL backend  (native OpenGL and WebGL2). Bevy will support it in upcoming 0.6 release, you can play with it now using pipelined-rendering branch: use https://github.com/bevyengine/bevy/tree/pipelined-rendering. Bevy 0.6 will also make this package obsolete and should support web out of the box (through GL wgpu backend).

**Comment by bekraoui** [comment]
Thank you for clarification. By the way i just tested the branch : `https://github.com/bevyengine/bevy/tree/pipelined-rendering` it didn't work. So i think i'll wait for 0.6 for full support of opengl.
